### ISSUE TITLE
are Kafka Streams supported

### ISSUE THREAD

**Issue by vladp** [Bogdanp/racket-kafka#2]
apologies in advance if this is out-of-scope
but wanted to understand if Kafka streams could be supported 

https://kafka.apache.org/0102/documentation/streams/developer-guide#streams_dsl

**Comment by Bogdanp** [comment]
My understanding of Kafka Streams (and please correct me if I'm wrong) is that they are "just" a Java DSL for processing topic data in a streaming style, but not something that exists at the protocol level. As such, I'm probably not going to implement that kind of API in this library, but that's something that could probably be built on top of it. I don't have any plans to do that, though.

**Comment by vladp** [comment]
ok, thank you.
